steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ocr-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ocr-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'ocr-app', '--image', 'gcr.io/$PROJECT_ID/ocr-app', '--platform', 'managed', '--region', 'asia-southeast1 ', '--allow-unauthenticated']
images:
  - 'gcr.io/$PROJECT_ID/ocr-app'
